-- Создание основной таблицы
CREATE TABLE mutations_foncieres (
    id SERIAL PRIMARY KEY,                      -- Суррогатный первичный ключ
    id_mutation TEXT,                           -- Исходный ID (object -> TEXT)
    date_mutation DATE,                         -- Дата операции (object -> DATE)
    numero_disposition INTEGER,                 -- Номер (int64 -> INTEGER)
    nature_mutation TEXT,                       -- Тип операции (object -> TEXT)
    valeur_fonciere NUMERIC(18, 2),             -- Стоимость (float64 -> NUMERIC для точности)
    adresse_numero NUMERIC(10, 0),                     -- Номер дома (float64 -> INTEGER, NULL если NaN)
    adresse_suffixe TEXT,                       -- Суффикс адреса (object -> TEXT)
    adresse_nom_voie TEXT,                      -- Название улицы (object -> TEXT)
    adresse_code_voie VARCHAR(10),              -- Код улицы (object -> VARCHAR, т.к. код)
    code_postal VARCHAR(10),                    -- Почтовый индекс (float64 -> VARCHAR, чтобы сохранить ведущие нули)
    code_commune VARCHAR(10),                   -- Код коммуны (object -> VARCHAR)
    nom_commune TEXT,                           -- Название коммуны (object -> TEXT)
    code_departement VARCHAR(5),                -- Код департамента (object -> VARCHAR)
    ancien_code_commune VARCHAR(10),            -- Старый код коммуны (float64 -> VARCHAR)
    ancien_nom_commune TEXT,                    -- Старое название коммуны (object -> TEXT)
    id_parcelle TEXT,                           -- ID участка (object -> TEXT)
    ancien_id_parcelle TEXT,                    -- Старый ID участка (object -> TEXT)
    numero_volume TEXT,                         -- Номер тома (object -> TEXT)
    lot1_numero TEXT,                           -- Номер лота 1 (object -> TEXT)
    lot1_surface_carrez NUMERIC(10, 2),         -- Площадь лота 1 (float64 -> NUMERIC)
    lot2_numero TEXT,                           -- Номер лота 2 (object -> TEXT)
    lot2_surface_carrez NUMERIC(10, 2),         -- Площадь лота 2 (float64 -> NUMERIC)
    lot3_numero TEXT,                           -- Номер лота 3 (object -> TEXT)
    lot3_surface_carrez NUMERIC(10, 2),         -- Площадь лота 3 (float64 -> NUMERIC)
    lot4_numero TEXT,                           -- Номер лота 4 (float64 -> TEXT, т.к. могут быть нечисловые или NaN)
    lot4_surface_carrez NUMERIC(10, 2),         -- Площадь лота 4 (float64 -> NUMERIC)
    lot5_numero TEXT,                           -- Номер лота 5 (object -> TEXT)
    lot5_surface_carrez NUMERIC(10, 2),         -- Площадь лота 5 (float64 -> NUMERIC)
    nombre_lots INTEGER,                        -- Количество лотов (int64 -> INTEGER)
    code_type_local NUMERIC(10, 0),                    -- Код типа помещения (float64 -> INTEGER, NULL если NaN)
    type_local TEXT,                            -- Тип помещения (object -> TEXT)
    surface_reelle_bati NUMERIC(10, 2),         -- Фактическая площадь застройки (float64 -> NUMERIC)
    nombre_pieces_principales NUMERIC(10, 0),          -- Количество основных комнат (float64 -> INTEGER, NULL если NaN)
    code_nature_culture VARCHAR(10),            -- Код типа земли (object -> VARCHAR)
    nature_culture TEXT,                        -- Тип земли (object -> TEXT)
    code_nature_culture_speciale VARCHAR(10),   -- Код спец. типа земли (object -> VARCHAR)
    nature_culture_speciale TEXT,               -- Спец. тип земли (object -> TEXT)
    surface_terrain NUMERIC(15, 2),             -- Площадь участка (float64 -> NUMERIC)
    longitude NUMERIC(10, 7),                   -- Долгота (float64 -> NUMERIC для точности)
    latitude NUMERIC(10, 7)                     -- Широта (float64 -> NUMERIC для точности)
);
